version: '3.8'

services:
  mysql_dev:
    image: mysql:8.0.28
    container_name: mysql_user_microservices
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: